### ISSUE TITLE
Dashboard does not scroll when content height exceeds the dashboard height

### ISSUE THREAD

**Issue by bkclerke** [umbraco/Umbraco.CMS.Backoffice#160]
**Issue:** When dashboards contain content height that exceeds the dashboard height, the dashboard does not scroll.

**Expected:** The dashboard content would scroll and not be cut off.

![image](https://user-images.githubusercontent.com/4968254/191960953-b4cd7d8b-40bd-4fd4-8a29-a8a6a669dfbc.png)

**Example Branch:** feature/published-dashboard

**Repro Steps:** 
1. Add UUI boxes to dashboard that exceed the height of the dashboard.

**Comment by markadrake** [comment]
# Same or Related Issue

I also see this issue in the `main` branch today.

The `<uui-scroll-container>`'s height is restricted for 2 reasons. First, `<umb-section-dashboards>` has no explicit height. The second cause for this behavior seems to be that the CSS selector: `#scroll-container` applies `height:500px` to the element. 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/713355/192155526-0e38eb56-37a4-42c6-bf56-ce50a6f8182b.png">

The overflow is scrollable:

https://user-images.githubusercontent.com/713355/192160037-c337068b-d6b3-4dd0-bed3-c236bc484cbe.mov

But obviously, there's unclaimed real estate on the screen.

# How to Remedy this in the Browser

- `<umb-section-dashboards>` was changed to `display:flex` and given `flex-direction:column;` and `height:100%`.
-  `<uui-scroll-container>` was given `flex-grow:1`.
   - The `height:500px` can be removed from `#scroll-container`. 

What I don't know:

- The architecture and intent of `<umb-section-dashboards>`. Will this component always contain `<uui-tab-group>` and `<uui-scroll-container>`? 
   - Are there other use cases? 
   - Do my CSS recommendations produce any side effects?

# Hopefully Constructive Feedback...

- I don't find it to be _great practice_ to use the `id` attribute for styling. I typically instruct others to forget the `id` attribute exists.
   - I think the CSS selector should match the component's name, in this case, `.uui-scroll-container`.
   - I believe CSS can be applied to the root with the `:host` selector. So applying any `id` or `class`(es) may be unnecessary.
- Is the use of two prefixes, `umb` and `uui`, intentional? I.E., does `umb` denote a UI element intended only to be used by Umbraco?

**Comment by mattbrailsford** [comment]
@markadrake just in response to your feedback

**1. CSS tartgeting IDs.**
You need to shift your mindset to component styling. All components styles are within the component and for the component only and so are scoped such that they will only ever affect the component itself. Generally speaking then, I think in this context targeting ID's is probably a good idea for styles that only affect a single element in the component, and class names can be used for things that repeat inside the component. Either way, the same rules as general css best practice don't really apply here.

**2. the use of `umb` and `uui`**
The `uui` prefix means the component comes from the UUI library. The purpose of the UUI library is to extract all resuable components and to define a consistant design language to be used by Umbraco (or any other project that decides to use them, such as the Umbraco Cloud Portal). These elements are generic and reusable. Think of these as bricks.

The `umb`  prefix means the components are the umbraco back office implementation. These are the business logic and layout instructions for the umbraco back office itself. You'll likely use some of these elements, but only in the context of extending Umbraco. They don't make sense outside of this context. Thinkg of these as the mortar / cement of the back office UI.

**Comment by nathanwoulfe** [comment]
Pretty sure this is resolved in latest - eg settings dashboard fills all vertical space and scrolls when content overflows viewport.

**Comment by bkclerke** [comment]
@nathanwoulfe It looks like this may still be an issue on other dashboards in the backoffice. For example, the [azure static app](https://ashy-bay-09f36a803.1.azurestaticapps.net/section/content/workspace/document/edit/all-property-editors-document-key/en-us/view/content) content node "All Property Editors" does not scroll and some of the properties are not visible.

![2023-03-20 16_35_46-Umbraco and 8 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/4968254/226488332-4b2ec61e-706d-449c-97c8-e46a060309ae.png)

**Comment by nathanwoulfe** [comment]
Oh fun! @bkclerke, I have a suspicion this will be due to slightly different implementations in different dashboards. Possible the changes to introduce `router-slot` have impacted here. I'll have a look and see what I can work out.

**Comment by iOvergaard** [comment]
I will create a new issue based on this!

**Comment by nathanwoulfe** [comment]
@iOvergaard I had a dig into this today, it looks like it's due to to the introduction of `umb-router-slot` and its child `router-slot`, which then needs to be styled consistently the whole way through the DOM. Will try to unravel it tomorrow.

**Comment by bkclerke** [comment]
I can scroll now on the azure site! thank you @nathanwoulfe :)

**Comment by nathanwoulfe** [comment]
@bkclerke glad to hear - it's possible that I didn't cover all the different scroll contexts, but should be fixed for dashboards and content. Let me know though if you find any busted bits.

**Comment by nielslyngsoe** [comment]
This will be fixed by this PR: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/745

Soon to be finished and merged, so I will close this issue :-)
