### ISSUE TITLE
[BUG]: Umbraco UI Issue: Section Selection and Removal Not Reflecting Changes

### ISSUE THREAD

**Issue by BishalTimalsina12** [umbraco/Umbraco.CMS.Backoffice#2015]
**Describe the bug**
When  "Selecting sections"  in the Umbraco backoffice  adding or removing sections from a content picker, the UI does not update dynamically to reflect the changes made untill i restart my project.

**To Reproduce**
1. Go to 'Users'
2. Click on 'User Groups'
3. Choose a section or remove existing section

**Expected behavior**
choosing or removing section should reflect the changes after i reload the page.

https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/143370089/70374655-cf6b-45a4-8ebf-848f10613afe

**Desktop (please complete the following information):**
 - OS: windows
 - Browser edge
 - Version 126.0.2592.61 (Official build) (64-bit)

**Additional context**

**Comment by iOvergaard** [comment]
Hello, and thanks for testing! There is currently some work going on to make sure the token is invalidated when you change user permissions. If it's alright with you, I would like to close this issue and refer to this other issue on the main tracker where this issue is being tracked: https://github.com/umbraco/Umbraco-CMS/issues/16523
