### ISSUE TITLE
Drop `lit-html` as direct dependency

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#579]
During the default setup of Storybook (v6) we got a direct dependency on `lit-html`. This dependency is also a transient dependency through `lit` itself. So the question is, do we need this direct dependency at all?

I noticed we accidentally import from it a few places outside of Storybook as well, which are easy to fix, so if we fix that, where do we stand on `lit-html`?

**Comment by mlukasz7** [comment]
Hi @iOvergaard I checked this topic and looks like it's possible to use only import `html` from `lit`. But I see that Umbraco Backoffice code imports also `ifDefined` and `when` from `lit-html/directives`. 
Because of this Umbraco Backoffice needs to have this helper functions and then will be possible to remove `lit-html` from the packages list.

**Comment by mlukasz7** [comment]
I removed all `lit-html` imports inside stories and a few places outside of Storybook and looks like it builds env and works well.

But I notices that `lit-html` is a dependency inside `@open-wc/testing`, `lit-element`, and `lit`. But in my opinion current state of the repository doesn't need this direct `lit-html` dependency at all. I can create PR with all updates in the code to review, because I still discover Umbraco and web components world :)
