### ISSUE TITLE
[BUG]: Issues with SDK/Packages 

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.CMS.Backoffice#884]
**Describe the bug**

Preview002

When working with extending the backoffice from an external project (not from within the Umbraco.CMS.Backoffice-repo) there are types that is not included in the published packages.

One example here is types from `/external/rxjs`, for example here:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/c0c6b493-4826-4f48-a41f-c3eb3caf2062)

Note that I'm using the `UmbObjectState`-object that extends `UmbDeepState` which is included, but `UmbDeepState` extends `BehaviorSubject` from RxJS and is referenced using `../../external/rsjs/index.js`, for some reason these types are not included in the package. Because of this TypeScript thinks that `getValue()` and `asObservable()` does not exist.

Does not look like I can solve this by installing RxJS since the `../../external/rsjs/index.js`-reference is not resolved to the installed RxJS-types.

I've noticed that other types used in snippets and samples in the docs are not accessible from external projects, one example is `UmbLitElement`, but I can get around this by extending `UmbElementMixin(LitElement)` for now. Same thing with `UmbRoute`.

I guess that the overall takeaway here is that HQ probably need to create some kind of sample-project that is not a part of the `Umbraco.CMS.Backoffice`-repository to verify that things work as expected and that any code-samples provided in documentation works in external projects.

**Comment by iOvergaard** [comment]
Thanks, @enkelmedia. We noticed this previously and it should be fixed in the next preview. If you want, you can try and install the latest npm package (tagged "next") to see if it is resolved there, but beware that other types have been moved around, so it probably wont work to build anything complex: https://www.npmjs.com/package/@umbraco-cms/backoffice/v/14.0.0-c074e160

It will land in the next preview release.
