### ISSUE TITLE
Dark mode theme

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.CMS.Backoffice#977]
**Is your feature request related to a problem? Please describe.**
I wonder if we should consider a dark mode theme in the new backoffice, e.g. allowing user to select "light", "dark" and "auto"?

**Describe the solution you'd like**
A dropdown/toggle to switch between light and dark mode - or based on system.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/2919859/69122866-23a0-4e65-ab93-c251daf21739)

**Describe alternatives you've considered**

**Additional context**

**Comment by iOvergaard** [comment]
Actually, we already built a stylesheet for this: https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/core/themes/themes/dark.theme.css

There's also a high-contrast stylesheet available: https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/core/themes/themes/high-contrast.theme.css

We even have a theme switcher UI somewhere, that can be shown in the current user modal, however, we had to put it on hold at some point since we couldn't get it to load the extra stylesheet properly after we removed Vite from the production build.

To enable it again, we need to figure out a way to copy the stylesheet to the production build. It's probably as simple as adding it to the rollup config, but since it's not a feature we have in the current backoffice, we decided to wait a bit with it.

If you want to pick it up, @bjarnef, you are most welcome to do so ☺️

**Comment by bjarnef** [comment]
@iOvergaard cool, yes I saw that - or the dropdown in the user overlay 😀
Any reason for the double "themes" folders in the path?

**Comment by iOvergaard** [comment]
@bjarnef the first "themes" is the name of the package, the second "themes" is the folder that contains the... themes 😂

**Comment by bjarnef** [comment]
@iOvergaard okay, makes a bit more sense 😅
Maybe call the package and "themes" folder something different to make it more clear? 🤔

`ui-themes`, `tinted-themes` or? 

Visual Studio seems to play with some new concepts like UI Refresh and tinted themes.
https://devblogs.microsoft.com/visualstudio/the-visual-studio-ui-refresh-preview-is-here/

**Comment by iOvergaard** [comment]
Yeah, we could eventually rename it, but I don't think that should be part of a dark-mode switcher.

**Comment by nielslyngsoe** [comment]
@bjarnef the css imports of extensions has been broken for a long time, but fixed in this PR. Therefor I will close this PR.

https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1031
