### ISSUE TITLE
Labelling the environment

### ISSUE THREAD

**Issue by drpeck** [umbraco/Umbraco.CMS.Backoffice#984]
Sometime my clients or I get confused which CMS we are currently operating in. This may be where we have different Umbraco projects, or different environments for the same project. These days with 100s of tabs we have open at a time, it's a little dangerous. It is easy therefore when you have similar content to make changes to the wrong project/ environment.

Ideal would be an optional config setting to put a title/ label. Even better would be being able to set a colour for the header.

A title might just make make the client feel like the system is built for them (like changing the login background). It might be possible to have a small optional banner underneath the header that could be configured to state "Staging Environment" or even "Frontend server - do not update content here".

**Comment by enkelmedia** [comment]
@drpeck Sounds like something that could be done with an extension in some way. Do you have any ideas of how you would like this to look visually? If you post some examples maybe we can figure out if it can be done with an extension.

It looks like the color of the header has it's own CSS-variable so it most likely something that can be built as a package.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/d2fd4b55-a0c3-410b-a3ec-c1afe6bd37fb)

**Comment by drpeck** [comment]
Unfortunately I'm not a frontend developer, and not visually creative, so I'm unhelpfully tabling a problem without a suggested solution. I imagined an additional slim banner below the main top bar, or text added to the left of the content app icons, but there are no doubt many better solutions to resolve this.

It's great to hear that this might be possible with an extension/ package. I would have thought it ideal to have this as a core feature, configured through appsettings.json. I appreciate that that might not be viable, especially if this is not a feature that has been requested previously. It just imagine that this would be useful to many.

**Comment by nielslyngsoe** [comment]
@drpeck Actually with this version of Backoffice it should be fairly easy to make such adjustments, like @enkelmedia proposes or as a label of some kind in the top right corner next to Global Search.

In Umbraco Cloud, this could be handled by the Cloud version of Deploy, which comes with a UI extension for Backoffice.
You might want to share this idea here [Umbraco Cloud Issues](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

But for now, I will remember this idea, and close it. Because the current scope of New Backoffice is to be feature complete with current. and this is a new feature in that perspective. But thanks again for your input!

**Comment by drpeck** [comment]
That makes sense
